// app/components/salesTableData.js

export const columns = [
  { id: "title", label: "Bid Title", minWidth: 180 },
  { id: "client", label: "Client Name", minWidth: 160 },
  { id: "due", label: "Due Date", minWidth: 120 },
  { id: "form", label: "MS Form", minWidth: 120 },
  { id: "goNoGo", label: "Go/No-Go Decision", minWidth: 160 },
  { id: "bidDecision", label: "Bid/No-Bid Decision", minWidth: 160 },
  { id: "guidanceReviewed", label: "Guidance Reviewed", minWidth: 160 },
  { id: "bidSubmitted", label: "Bid Submitted", minWidth: 140 },
  { id: "bidAccepted", label: "Bid Accepted", minWidth: 140 },
  { id: "action", label: "Action", minWidth: 140 },
];

export const initialRows = [
  {
    title: "Bid Title 1",
    client: "Client Name",
    due: "2023-11-01",
    form: "MS Form",
    goNoGo: "Go",
    bidDecision: "Bid",
    guidanceReviewed: true,
    bidSubmitted: true,
    bidAccepted: false,
  },
  {
    title: "Bid Title 2",
    client: "Client Alpha",
    due: "2023-11-15",
    form: "MS Form",
    goNoGo: "Go",
    bidDecision: "No-Bid",
    guidanceReviewed: false,
    bidSubmitted: false,
    bidAccepted: false,
  },
  {
    title: "Bid Title 3",
    client: "Client Beta",
    due: "2023-12-01",
    form: "MS Form",
    goNoGo: "Go",
    bidDecision: "Pending",
    guidanceReviewed: true,
    bidSubmitted: false,
    bidAccepted: false,
  },
  {
    title: "Bid Title 4",
    client: "Client Gamma",
    due: "2023-11-30",
    form: "MS Form",
    goNoGo: "No-Go",
    bidDecision: "Pending",
    guidanceReviewed: false,
    bidSubmitted: false,
    bidAccepted: false,
  },
  {
    title: "Bid Title 5",
    client: "Client Delta",
    due: "2023-10-25",
    form: "MS Form",
    goNoGo: "Pending",
    bidDecision: "Pending",
    guidanceReviewed: false,
    bidSubmitted: false,
    bidAccepted: false,
  },
  {
    title: "Bid Title 6",
    client: "Client Epsilon",
    due: "2024-01-10",
    form: "MS Form",
    goNoGo: "Go",
    bidDecision: "Bid",
    guidanceReviewed: true,
    bidSubmitted: true,
    bidAccepted: true,
  },
];
